"""add_slug_to_events

Revision ID: 7f533b0f9e1d
Revises: 1b7590c330c7
Create Date: 2026-04-19 19:49:36.318639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f533b0f9e1d'
down_revision: Union[str, Sequence[str], None] = '1b7590c330c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('slug', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'events', ['slug'])
    op.drop_column('events', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_column('events', 'slug')
    # ### end Alembic commands ###
