"""add_title_specializations_to_trainers

Revision ID: c3fcac5964b7
Revises: 7f533b0f9e1d
Create Date: 2026-04-19 19:57:58.559143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fcac5964b7'
down_revision: Union[str, Sequence[str], None] = '7f533b0f9e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainers', sa.Column('title', sa.String(), nullable=True))
    op.add_column('trainers', sa.Column('specializations', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainers', 'specializations')
    op.drop_column('trainers', 'title')
    # ### end Alembic commands ###
